//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using UnityEngine;
using System.Collections;
using System.Collections.Generic;

[System.Serializable]
public class SwoonNode
{
	public string clipname;
	public int end = 0,start = 0;
}

public class SwooshNew : MonoBehaviour
{

	public SwoonNode[] _animations;
	AnimatorStateInfo _animationState;
	float _startN = 0.0f;
	float _endN = 0.0f;
	
	float _time = 0.0f;
	//float _prevTime = 0.0f;
	//float _prevAnimTime = 0.0f;
	

	public List<MeleeWeaponTrail> _trails;
	
	//bool _firstFrame = true;
	Animator mAnimator;
	void Start()
	{
		mAnimator = GetComponent<Animator> ();
		_trails.ForEach(x=>x.Emit = false);
	}
	
	void Update()
	{
		_startN = 0.0f;
		_endN = 0.0f;
		_animationState = mAnimator.GetCurrentAnimatorStateInfo (0);

		SwoonNode snode = System.Array.Find (_animations, xx => _animationState.IsName (xx.clipname));
		if (snode != null) 
		{
			_time = _animationState.normalizedTime - Mathf.Floor(_animationState.normalizedTime);
			float frames = (int)(_animationState.length*30);
			_startN = snode.start / frames;
			_endN = snode.end / frames;
			if (_time >= _startN && _time < _endN) 
			{
				_trails.ForEach(x=>x.Emit = true);
			}
			else
			{
				_trails.ForEach(x=>x.Emit = false);
			}
		}
		else
		{
			_time = 0f;
			//_prevTime = _time;
			//_prevAnimTime = 0f;
		}
	}
}